version: '2'
services:
  ddagent:
    container_name: ddagent
    image: datadog/docker-dd-agent
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=bf09b615f016c4dd0ed84a9cd1677f1c
    ports:
      - "8126:8126"

  todolist:
    container_name: todolist
    image: todolist
    # restart: always
    env_file: .env
    command: gunicorn todolist:app -w 2 -b :8000
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - ddagent

  migration:
    container_name: migration
    build: .
    image: todolist
    env_file: .env
    command: flask db upgrade
    volumes:
      - .:/code
